bucky/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^muz/', include('music.urls')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

music/urls.py
from django.conf.urls import url
from . import views

app_name = 'music'
urlpatterns = [
    #/muz/
    url(r'^register/$', views.UserFormView.as_view(), name = "register"),
    url(r'^$', views.IndexView.as_view(), name='index'),
    #/muz/101/
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name="detail"),
    url(r'^album/add/$', views.AlbumCreate.as_view(), name="album-add"),
    url(r'^album/(?P<pk>[0-9]+)/$', views.AlbumUpdate.as_view(), name="album-update"),
    url(r'^album/(?P<pk>[0-9]+)/delete/$', views.AlbumDelete.as_view(), name="album-delete"),
]

music/models.py
from django.db import models
from django.core.urlresolvers import reverse


# Create your models here.
class Album(models.Model):
    artist = models.CharField(max_length=100)
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    album_logo = models.FileField()

    def get_absolute_url(self):
        return reverse('music:detail', kwargs={'pk':self.pk})

    def __str__(self):
        return self.album_title

class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=200)
    def __str__(self):
        return self.song_title

music/forms.py
from django.contrib.auth.models import User
from django import forms

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

music/views.py
from .models import Album,Song
from django.views import generic
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate, login
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from django.views.generic import View
from music.forms import UserForm


class IndexView(generic.ListView):
    template_name = 'music/index.html'
    context_object_name = 'all_albums'
    def get_queryset(self):
        return Album.objects.all()

class DetailView(generic.DetailView):
    model = Album
    template_name = 'music/detail.html'

class AlbumCreate(CreateView):
    model = Album
    fields = ['artist','album_title','genre','album_logo']

class AlbumUpdate(UpdateView):
    model = Album
    fields = ['artist','album_title','genre','album_logo']
class AlbumDelete(DeleteView):
    model = Album
    success_url = reverse_lazy('music:index')

class UserFormView(View):
    form_class = UserForm
    template_name = 'music/registration_form.html'

    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name,{'form':form})

    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():
            user = form.save(commit=False)
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()

            user = authenticate(username=username, password=password)

            if user is not None:

                if user.is_active:
                    login(request, user)
                    return redirect('music:index')
        return render(request, self.template_name,{'form':form})

templates/music/album_form.html
{% extends 'music/base.html' %}
{% block title %}Add Album {% endblock %}
{% block content %}

<div class="ui grid">
<br>
<form class="ui form" action="" method="post" enctype="multipart/form-data">
{% csrf_token %}
{% include 'music/form-template.html' %}

<button type="submit" name="button" class="ui button">Add Album</button>

</form>

</div>

{% endblock %}

templates/music/base.html
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <title>{% block title %}Music {% endblock %}</title>
    <link rel="stylesheet" href="{% static "semantic.min.css" %}">
    <link rel="stylesheet" href="{% static "components/image.min.css" %}">

    <!-- main styles -->
    <link rel="stylesheet" href="{% static "main.css" %}">
  </head>
  <body>
    <div class="ui container">
<div class="ui secondary pointing menu">
  <a class="item active" href="{% url 'music:index' %}">
    Albums
  </a>
  <a class="item ">
    Songs
  </a>

  <div class="right menu">
    <a class="item" href="{% url 'music:album-add'%}">
       + Add Album
    </a>
   <a class="ui item">
     <i class="sign out icon"></i>
     Logout
   </a>
 </div>
</div>

<div class="ui container">

   {% block content %}
   {% endblock %}
</div>

<script
  src="https://code.jquery.com/jquery-3.1.1.min.js"
  integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
  crossorigin="anonymous"></script>
<script src="{% static "semantic.min.js" %}" type="text/javascript">

</script>
  </body>
</html>

templates/music/detail.html
{% extends 'music/base.html' %}
{% load staticfiles %}
{% block title %} Songs {% endblock %}

{% block content %}

<h1 class="ui header">{{album.album_title}}</h1>
<h3>By: {{album.artist}}</h3>

<div class="ui grid">
  <div class="four wide column"><img src="{{album.album_logo.url}}"  class="ui image"></div>
  <div class="eight wide column">
    <div class="ui divided items">
      {% for song in album.song_set.all %}
      <div class="item">{{song.song_title}}.{{song.file_type}}</div>

      {% endfor %}
    </div>
  </div>



<div>

{% endblock %}

templates/music/form-template.html
{% for field in form %}

<div class="field">
  <span class="red">{{ field.errors }}</span>
    <label>{{field.label_tag}}</label>

      <div class="field">
        {{ field }}
      </div>

    </div>

{% endfor %}

templates/music/index.html
{% extends 'music/base.html' %}
{% load staticfiles %}
{% block content %}
<div class="item">
  <div class="ui icon input">
    <input type="text" placeholder="Search...">
    <i class="search link icon"></i>
  </div>
</div>
          <h1 class="ui header">My Albums</h1>
          <br>
      {% if all_albums %}

      <div class="ui three column grid">

          <div class="row">
{% for album in all_albums %}
              <div class="ui column">

              <a href="{% url 'music:detail' album.id %}" class="ui medium image"><h3 class="ui header">{{album.album_title}}</h3>
                <img src="{{album.album_logo.url}}" alt="" class="ui image">
              </a>
              <br><br><br>
              <div class="ui divided grid padbot">
                  <div class="row">
                     <div class="six wide column">
                       <a href="{% url 'music:detail' album.id %}" class="ui primary basic button">View Songs</a>
                     </div>
                     <div class="four wide column">
                       <form class="inline" action="{% url 'music:album-delete' album.id %}" method="post">
                         {% csrf_token %}

                         <button class="ui inverted red button" type="submit">Delete</button>
                       </form>

                     </div>

                  </div>
              </div>


            </div>
  {% endfor %}
          </div>
          <br>  <br>  <br>

      </div>

      {% else %}
      <h2>No albums<h2>
      {% endif %}

        </div>
{% endblock %}

templates/music/registration_form.html
{% extends 'music/base.html' %}
{% block title %}Register{% endblock %}
{% block content %}

<div class="ui grid">
<br>
<form class="ui form" action="" method="post" enctype="multipart/form-data">
  <legend>Create an Account</legend>
{% csrf_token %}
{% include 'music/form-template.html' %}

<button type="submit" name="button" class="ui button">Register</button>

</form>

</div>

{% endblock %}